In [2]:
import pandas as pd

# Reading data from CSV file using Pandas DataFrame

In [3]:
pd.read_csv("data/course_offerings.csv", sep=",")

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [4]:
pd.read_csv("data/course_offerings.csv", sep=",", header='infer')

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [5]:
pd.read_csv("data/course_offerings.csv", sep=",", header=None)

           0                            1             2
0  course_id                  course_name    instructor
1        101              Intro to Python  Chris Bruehl
2        102                 Intro to SQL   John Pauler
3        201    Exploratory Data Analysis    Alice Zhao
4        301                   Algorithms  Chris Bruehl
5        331  Natural Language Processing    Alice Zhao

# Reading data from XLSX file using Pandas DataFrame

In [6]:
pd.read_excel("data/Course Offerings.xlsx")

     Instructor                    Title
0  Chris Bruehl   Lead Python Instructor
1   John Pauler     Chief Growth Officer
2    Alice Zhao  Data Science Instructor

In [7]:
pd.read_excel("data/Course Offerings.xlsx", sheet_name=1)

   Course ID                  Course Name    Instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

# Reading data from database using Pandas DataFrame

In [8]:
import sqlite3

In [9]:
conn = sqlite3.connect('data/maven.db')

In [10]:
pd.read_sql("SELECT * FROM courses", conn)

   course_id                       course    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

# Saving the DataFrame after reading it from the source

In [11]:
df = pd.read_csv('data/course_offerings.csv')

In [12]:
df

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

# Exploring the DataFrame

In [13]:
df.head(2)

   course_id      course_name    instructor
0        101  Intro to Python  Chris Bruehl
1        102     Intro to SQL   John Pauler

In [14]:
df.tail(2)

   course_id                  course_name    instructor
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [15]:
df.shape

(5, 3)

In [16]:
df.count()

course_id      5
course_name    5
instructor     5
dtype: int64

In [17]:
df.describe()

        course_id
count    5.000000
mean   207.200000
std    107.829495
min    101.000000
25%    102.000000
50%    201.000000
75%    301.000000
max    331.000000

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   course_id    5 non-null      int64
 1   course_name  5 non-null      str
 2   instructor   5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes