In [2]:
import pandas as pd

In [6]:
pd.read_csv("data/course_offerings.csv", sep=",")

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [9]:
pd.read_csv("data/course_offerings.csv", sep=",", header='infer')

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [10]:
pd.read_csv("data/course_offerings.csv", sep=",", header=None)

           0                            1             2
0  course_id                  course_name    instructor
1        101              Intro to Python  Chris Bruehl
2        102                 Intro to SQL   John Pauler
3        201    Exploratory Data Analysis    Alice Zhao
4        301                   Algorithms  Chris Bruehl
5        331  Natural Language Processing    Alice Zhao