In [1]:
import pandas as pd

# Reading data from CSV file using Pandas DataFrame

In [2]:
pd.read_csv("data/course_offerings.csv", sep=",")

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [3]:
pd.read_csv("data/course_offerings.csv", sep=",", header='infer')

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [4]:
pd.read_csv("data/course_offerings.csv", sep=",", header=None)

           0                            1             2
0  course_id                  course_name    instructor
1        101              Intro to Python  Chris Bruehl
2        102                 Intro to SQL   John Pauler
3        201    Exploratory Data Analysis    Alice Zhao
4        301                   Algorithms  Chris Bruehl
5        331  Natural Language Processing    Alice Zhao

# Reading data from XLSX file using Pandas DataFrame

In [6]:
pd.read_excel("data/Course Offerings.xlsx")

     Instructor                    Title
0  Chris Bruehl   Lead Python Instructor
1   John Pauler     Chief Growth Officer
2    Alice Zhao  Data Science Instructor

In [7]:
pd.read_excel("data/Course Offerings.xlsx", sheet_name=1)

   Course ID                  Course Name    Instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao