# 1. Data Types conversion of DataFrames

In [30]:
import pandas as pd

#### Loading raw data file for Pandas to read it

In [31]:
run_time = pd.read_excel('data/Run Times.xlsx')
run_time

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,$0.00
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,$0.00
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,$2.50
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,$0.00
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,$2.50

#### Checking the DataTypes of each column

In [32]:
run_time.dtypes

Name                       str
Run Time               float64
Warm Up Time            object
Location                   str
Run Date        datetime64[us]
Race Date       datetime64[us]
Rain                      bool
Fee                        str
dtype: object

### Objectives:

- The `Warm Up Time` column is currently of dtype `object` because the second row contains mixed data (3 min). We need to clean the values and convert the column to a float.
- The `Fee` column is stored as a `string` because it includes the `$` symbol. We need to remove the `$` symbol and then convert the column to a float.

In [33]:
run_time

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,$0.00
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,$0.00
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,$2.50
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,$0.00
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,$2.50

In [34]:
# Working on Fee Column as per our objective

pd.to_numeric(run_time.Fee.str.replace('$',''))

0    0.0
1    0.0
2    2.5
3    0.0
4    2.5
Name: Fee, dtype: float64

In [35]:
# Working on `Warm Up Time` Column as per our objective

pd.to_numeric(run_time['Warm Up Time'], errors='coerce')

0    3.5
1    3.5
2    NaN
3    2.2
4    2.0
Name: Warm Up Time, dtype: float64

In [36]:
# now column's data type converted to float64 but 2nd column value changed to NaN
# So first we need to remove the `min` from the Warm Up Time (google: str.replace nan).DS_Store

run_time['Warm Up Time'].str.replace(' min', '')

0    NaN
1    NaN
2      3
3    NaN
4    NaN
Name: Warm Up Time, dtype: object

In [37]:
# above method also fails as now the problematic column corrected
# but other column value changed to Nan and still data type is object.

# Therefor we can use astype() to replace the string min.

pd.to_numeric(run_time['Warm Up Time'].astype('str').str.replace(' min', ''))

0    3.5
1    3.5
2    3.0
3    2.2
4    2.0
Name: Warm Up Time, dtype: float64

In [24]:
# change the Rain column from boolean to int

run_time.Rain.astype('int')

0    0
1    1
2    0
3    0
4    0
Name: Rain, dtype: int64

In [25]:
run_time.dtypes

Name                       str
Run Time               float64
Warm Up Time            object
Location                   str
Run Date        datetime64[us]
Race Date       datetime64[us]
Rain                      bool
Fee                        str
dtype: object

# 2. Handelling missing value in DataFrames

In [38]:
SG = pd.read_excel('data/Student Grades.xlsx')
SG

    Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman   86.0
1    Olivia  Freshman Seminar  Freshman   86.0
2      Noah  Freshman Seminar  Freshman   86.0
3    Sophia  Freshman Seminar  Freshman   87.0
4      Liam  Freshman Seminar  Freshman   90.0
..      ...               ...       ...    ...
81      NaN               NaN       NaN    NaN
82  Bennett               NaN       NaN    NaN
83      NaN               EDA    Junior   84.0
84    Gavin               EDA    Senior    NaN
85   Calvin               NaN       NaN  100.0

[86 rows x 4 columns]

In [39]:
SG.dtypes

Student        str
Class          str
Year           str
Grade      float64
dtype: object